services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dronegestory-backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      # SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
      # SPRING_DATASOURCE_USERNAME: ${DB_USER}
      # SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      # SPRING_JPA_HIBERNATE_DDL_AUTO: update
      - SERVER_IP=${SERVER_IP}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - drone_network

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_BASE_URL=https://${SERVER_IP}:8080
    container_name: dronegestory-frontend
    ports:
      - "8081:80"
    depends_on:
      - backend
    networks:
      - drone_network

  db:
    image: postgres:16
    container_name: dronegestory-db
    restart: always
    environment:
      # POSTGRES_USER: admin
      # POSTGRES_PASSWORD: admin123
      # POSTGRES_DB: aeronaves_db
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    # ports:
    #   - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - drone_network

volumes:
  postgres_data:

networks:
  drone_network:
    driver: bridge