import type { Anexo4Fields } from "../operations/operation.types";

export const ANEXO4_INITIAL_FIELDS: Anexo4Fields = {
  descripcion: "",
  fechaHoraPrevista: "",
  mediosMateriales: "",
  direccion: "",
  coords: "",
  personal: "",
  imagenEspacioAereo: "",
  imagenZonaVuelo: "",
  espacioAereoControlado: "",
  estudioAeronauticoCoordinado: "",
  entornoAerodromos: "",
  distanciaMinimaInfraestructuras: "",
  zonasProhibidasFlexible: "",
  cumpleCondiciones: "",
  zonasSeguridad: "",
  permisoPrevioSeguridad: "",
  serviciosEsencialesComunidad: "",
  permisoPrevioServicios: "",
  entornosUrbanos: "",
  cumplenDistanciasEdificios: "",
  comunicacionMinisterioInterior: "",
  zonaResVueloFotografico: "",
  permisoCecaf: "",
  zonasProtMedioambiental: "",
  disponeCoordGestor: "",
  conopsYModeloSemantico: "",
  aplicaModelo: "",
  defineGeografiaVueloConops: "",
  defineVolContigencia: "",
  defineMargenRiesgoTierra: "",
  defineZonaTerrestreControlada: "",
  planificaUbicacionObservadores: "",
  calculaAreaYEvaluaRiesgo: "",
  notams: "",
  revisaNotams: "",
  tsaOCondicionada: "",
  otrasLimitaciones: "",
};

export const BOOLEAN_FIELD_LABELS: Record<string, string> = {
  espacioAereoControlado: "4.1 Espacio aéreo controlado",
  estudioAeronauticoCoordinado: "4.1.1 Estudio aeronáutico coordinado",
  entornoAerodromos: "4.2 Entorno de aeródromos",
  distanciaMinimaInfraestructuras: "4.2.1 Distancia mínima a infraestructuras",
  zonasProhibidasFlexible: "4.3 Zonas prohibidas / flexibles",
  cumpleCondiciones: "4.3.1 Cumple condiciones",
  zonasSeguridad: "4.4 Zonas de seguridad",
  permisoPrevioSeguridad: "4.4.1 Permiso previo de seguridad",
  serviciosEsencialesComunidad: "4.5 Servicios esenciales de la comunidad",
  permisoPrevioServicios: "4.5.1 Permiso previo de servicios",
  entornosUrbanos: "4.6 Entornos urbanos",
  cumplenDistanciasEdificios: "4.6.1 Cumplen distancias a edificios",
  comunicacionMinisterioInterior: "4.6.2 Comunicación al Ministerio del Interior",
  zonaResVueloFotografico: "4.7 Zona de vuelo fotográfico",
  permisoCecaf: "4.7.1 Permiso CECAF",
  zonasProtMedioambiental: "4.8 Zonas de protección medioambiental",
  disponeCoordGestor: "4.8.1 Dispone de coordinación con el gestor",
  conopsYModeloSemantico: "6.1 CONOPS y modelo semántico",
  aplicaModelo: "6.1.1 Aplica modelo",
  defineGeografiaVueloConops: "6.1.2 Define geografía de vuelo en CONOPS",
  defineVolContigencia: "6.1.3 Define volumen de contingencia",
  defineMargenRiesgoTierra: "6.1.4 Define margen de riesgo en tierra",
  defineZonaTerrestreControlada: "6.1.5 Define zona terrestre controlada",
  planificaUbicacionObservadores: "6.1.6 Planifica ubicación de observadores",
  calculaAreaYEvaluaRiesgo: "6.1.7 Calcula área y evalúa riesgo",
  notams: "6.2 NOTAMs",
  revisaNotams: "6.2.1 Revisa NOTAMs",
  tsaOCondicionada: "6.2.2 TSA o condicionada",
  otrasLimitaciones: "6.3 Otras limitaciones",
};

export const BOOLEAN_FIELDS_SECTION4 = [
  "espacioAereoControlado",
  "estudioAeronauticoCoordinado",
  "entornoAerodromos",
  "distanciaMinimaInfraestructuras",
  "zonasProhibidasFlexible",
  "cumpleCondiciones",
  "zonasSeguridad",
  "permisoPrevioSeguridad",
  "serviciosEsencialesComunidad",
  "permisoPrevioServicios",
  "entornosUrbanos",
  "cumplenDistanciasEdificios",
  "comunicacionMinisterioInterior",
  "zonaResVueloFotografico",
  "permisoCecaf",
  "zonasProtMedioambiental",
  "disponeCoordGestor",
] as const;

export const BOOLEAN_FIELDS_SECTION6 = [
  "conopsYModeloSemantico",
  "aplicaModelo",
  "defineGeografiaVueloConops",
  "defineVolContigencia",
  "defineMargenRiesgoTierra",
  "defineZonaTerrestreControlada",
  "planificaUbicacionObservadores",
  "calculaAreaYEvaluaRiesgo",
  "notams",
  "revisaNotams",
  "tsaOCondicionada",
  "otrasLimitaciones",
] as const;
