import type { FieldConfig } from "../FieldConfig";

export const operationAnexo6DetailFields: FieldConfig[] = [
  { label: "CONOPS", key: "nombreConops", type: "text" },
  { label: "Fecha operación", key: "fechaOp", type: "date" },
  // Puedes añadir campo para materialesAuxiliares si quieres gestionarlo vía campos
  { label: "Sin impacto", key: "sinImpacto", type: "boolean" },
  { label: "Centro gravedad", key: "centroGravedad", type: "boolean" },
  { label: "Integridad estructural", key: "integridadEstructural", type: "boolean" },
  { label: "Cableado", key: "cableado", type: "boolean" },
  { label: "Verificación luces", key: "verificacionLuces", type: "boolean" },
  { label: "Calibración", key: "calibracion", type: "boolean" },
  { label: "Validar salida datos", key: "validarSalidaDatos", type: "boolean" },
  { label: "Giran libremente", key: "giranLibremente", type: "boolean" },
  { label: "Sentido giro correcto", key: "sentidoGiroCorrecto", type: "boolean" },
  { label: "Sin impacto motores", key: "sinImpactoMotores", type: "boolean" },
  { label: "Colocación correcta", key: "colocacionCorrecta", type: "boolean" },
  { label: "Sujeción firme", key: "sujetacionFirme", type: "boolean" },
  { label: "Sin impacto hélices", key: "sinImpactoHelices", type: "boolean" },
  { label: "Batería carga", key: "bateriaCarga", type: "boolean" },
  { label: "Movimiento fluido mando", key: "movimientoFluidoMando", type: "boolean" },
  { label: "Sin impacto partes móviles", key: "sinImpactoPartesMoviles", type: "boolean" },
  { label: "Movimiento fluido partes móviles", key: "movimientoFluidoPartesMoviles", type: "boolean" },
  { label: "Antenas instaladas y orientadas", key: "antenasInstaladasYOrientadas", type: "boolean" },
  { label: "Calidad onda", key: "calidadOnda", type: "boolean" },
  { label: "Recepción adecuada", key: "recepcionAdecuada", type: "boolean" },
  { label: "Fuente alimentación", key: "fuenteAlimentacion", type: "boolean" },
  { label: "Nivel fuente alimentación", key: "nivelFuenteAlimentacion", type: "boolean" },
  { label: "Fijación correcta", key: "fijacionCorrecta", type: "boolean" },
  { label: "Memoria suficiente para datos", key: "memoriaSuficienteParaDatos", type: "boolean" },
  { label: "Sin impacto carga de pago", key: "sinImpactoCargaPago", type: "boolean" },
  { label: "Conexiones carga de pago", key: "conexionesCargaPago", type: "boolean" },
  { label: "Datos cargados", key: "datosCargados", type: "boolean" },
  { label: "Transmisión de datos", key: "transmisionDatos", type: "boolean" },
  { label: "Información actualizada", key: "informacionActualizada", type: "boolean" },
  { label: "Sistema activado", key: "sistemaActivado", type: "boolean" },
];