import type { FieldConfig } from "../FieldConfig";

export const operationAnexo7DetailFields: FieldConfig[] = [
  { label: "CONOPS", key: "nombreConops", type: "text" },
  { label: "Fecha operación", key: "fechaOp", type: "date" },
  { label: "Estructura", key: "estructuraCorrecto", type: "boolean" },
  { label: "Estructura Observaciones", key: "estructuraObservaciones", type: "text" },
  { label: "Baterías", key: "bateriasCorrecto", type: "boolean" },
  { label: "Baterías Observaciones", key: "bateriasObservaciones", type: "text" },
  { label: "Sensores", key: "sensoresCorrecto", type: "boolean" },
  { label: "Sensores Observaciones", key: "sensoresObservaciones", type: "text" },
  { label: "Motores", key: "motoresCorrecto", type: "boolean" },
  { label: "Motores Observaciones", key: "motoresObservaciones", type: "text" },
  { label: "Hélices", key: "helicesCorrecto", type: "boolean" },
  { label: "Hélices Observaciones", key: "helicesObservaciones", type: "text" },
  { label: "Partes móviles", key: "partesMovilesCorrecto", type: "boolean" },
  { label: "Partes móviles Observaciones", key: "partesMovilesObservaciones", type: "text" },
  { label: "Comunicaciones", key: "comunicacionesCorrecto", type: "boolean" },
  { label: "Comunicaciones Observaciones", key: "comunicacionesObservaciones", type: "text" },
  { label: "Planta potencia", key: "plantaPotenciaCorrecto", type: "boolean" },
  { label: "Planta potencia Observaciones", key: "plantaPotenciaObservaciones", type: "text" },
  { label: "Carga de pago", key: "cargaPagoCorrecto", type: "boolean" },
  { label: "Carga de pago Observaciones", key: "cargaPagoObservaciones", type: "text" },
  { label: "Identificación remota", key: "identificacionRemotaCorrecto", type: "boolean" },
  { label: "Identificación remota Observaciones", key: "identificacionRemotaObservaciones", type: "text" },
  { label: "Sistema geoconsciencia", key: "sistemaGeoconscienciaCorrecto", type: "boolean" },
  { label: "Sistema geoconsciencia Observaciones", key: "sistemaGeoconscienciaObservaciones", type: "text" },
  { label: "Datos de vuelo", key: "datosVueloCorrecto", type: "boolean" },
  { label: "Datos de vuelo Observaciones", key: "datosVueloObservaciones", type: "text" },
  { label: "Otros verificación", key: "otrosVerificacionCorrecto", type: "boolean" },
  { label: "Otros verificación Observaciones", key: "otrosVerificacionObservaciones", type: "text" },
  { label: "Aeronave", key: "aeronaveCorrecto", type: "boolean" },
  { label: "Aeronave Observaciones", key: "aeronaveObservaciones", type: "text" },
  { label: "Unidad de control", key: "unidadControlCorrecto", type: "boolean" },
  { label: "Unidad de control Observaciones", key: "unidadControlObservaciones", type: "text" },
  { label: "Sensores recogida", key: "sensoresRecogidaCorrecto", type: "boolean" },
  { label: "Sensores recogida Observaciones", key: "sensoresRecogidaObservaciones", type: "text" },
  { label: "Antenas", key: "antenasCorrecto", type: "boolean" },
  { label: "Antenas Observaciones", key: "antenasObservaciones", type: "text" },
  { label: "Otros recogida", key: "otrosRecogidaCorrecto", type: "boolean" },
  { label: "Otros recogida Observaciones", key: "otrosRecogidaObservaciones", type: "text" },
];