--
-- PostgreSQL database dump
--

\restrict u3HbdZlu1uchW7EN5GYIcb7CBFKNJzGbHhtq3F545BDFjhzgJUbofcW0n3GIyXR

-- Dumped from database version 16.14 (Debian 16.14-1.pgdg13+1)
-- Dumped by pg_dump version 16.14 (Debian 16.14-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: admin
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO admin;

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: admin
--

COMMENT ON SCHEMA public IS '';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: aircraft; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.aircraft (
    aircraft_id bigint NOT NULL,
    accessories character varying(800),
    class character varying(255) NOT NULL,
    cautive character varying(20),
    config character varying(255) NOT NULL,
    fecha_fab date,
    flight_minutes integer DEFAULT 0 NOT NULL,
    camera boolean NOT NULL,
    has_ensurance boolean,
    has_fts boolean,
    has_parachute boolean,
    image_path character varying(255),
    impact_energy numeric(9,3) NOT NULL,
    max_speed numeric(9,3) NOT NULL,
    mtom numeric(9,3) NOT NULL,
    power_source smallint,
    power_source_type smallint,
    privately_built boolean,
    serial_number character varying(255) NOT NULL,
    wingspan numeric(9,3) NOT NULL,
    aircraft_model_id bigint NOT NULL,
    max_autonomy numeric(9,3),
    observations character varying(800),
    CONSTRAINT aircraft_cautive_check CHECK (((cautive)::text = ANY (ARRAY[('YES'::character varying)::text, ('NO'::character varying)::text, ('OPTIONAL'::character varying)::text]))),
    CONSTRAINT aircraft_class_check CHECK (((class)::text = ANY (ARRAY[('No'::character varying)::text, ('C0'::character varying)::text, ('C1'::character varying)::text, ('C2'::character varying)::text, ('C3'::character varying)::text, ('C4'::character varying)::text, ('Legacy'::character varying)::text]))),
    CONSTRAINT aircraft_config_check CHECK (((config)::text = ANY (ARRAY[('Hibrido_vtol'::character varying)::text, ('Avion'::character varying)::text, ('Multirrotor'::character varying)::text, ('Helicoptero'::character varying)::text, ('Hibrido'::character varying)::text, ('Ligero'::character varying)::text, ('Otro'::character varying)::text]))),
    CONSTRAINT aircraft_power_source_check CHECK (((power_source >= 0) AND (power_source <= 1))),
    CONSTRAINT aircraft_power_source_type_check CHECK (((power_source_type >= 0) AND (power_source_type <= 2)))
);


ALTER TABLE public.aircraft OWNER TO admin;

--
-- Name: aircraft_aircraft_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.aircraft ALTER COLUMN aircraft_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.aircraft_aircraft_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: aircraft_documentation; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.aircraft_documentation (
    aircraft_documentation_id bigint NOT NULL,
    date_indefinite boolean,
    documentation_name character varying(255),
    documentation_type character varying(255),
    expire_date date,
    aircraft_id bigint NOT NULL,
    aircraft_model_documentation_id bigint
);


ALTER TABLE public.aircraft_documentation OWNER TO admin;

--
-- Name: aircraft_documentation_aircraft_documentation_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.aircraft_documentation ALTER COLUMN aircraft_documentation_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.aircraft_documentation_aircraft_documentation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: aircraft_model; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.aircraft_model (
    id bigint NOT NULL,
    accessories_default character varying(800),
    aircraft_class_default character varying(255),
    cautive_default character varying(20),
    config_default character varying(255),
    has_camera_default boolean,
    has_fts_default boolean,
    has_parachute_default boolean,
    image_path character varying(255),
    impact_energy_default numeric(9,3),
    manufacturer character varying(100) NOT NULL,
    max_speed_default numeric(9,3),
    model character varying(100) NOT NULL,
    mtom_default numeric(9,3),
    power_source_default character varying(20),
    power_source_type_default character varying(20),
    privately_built_default boolean,
    wingspan_default numeric(9,3),
    max_autonomy_default numeric(9,3),
    observations_default character varying(800),
    CONSTRAINT aircraft_model_aircraft_class_default_check CHECK (((aircraft_class_default)::text = ANY (ARRAY[('No'::character varying)::text, ('C0'::character varying)::text, ('C1'::character varying)::text, ('C2'::character varying)::text, ('C3'::character varying)::text, ('C4'::character varying)::text, ('Legacy'::character varying)::text]))),
    CONSTRAINT aircraft_model_cautive_default_check CHECK (((cautive_default)::text = ANY (ARRAY[('YES'::character varying)::text, ('NO'::character varying)::text, ('OPTIONAL'::character varying)::text]))),
    CONSTRAINT aircraft_model_config_default_check CHECK (((config_default)::text = ANY (ARRAY[('Hibrido_vtol'::character varying)::text, ('Avion'::character varying)::text, ('Multirrotor'::character varying)::text, ('Helicoptero'::character varying)::text, ('Hibrido'::character varying)::text, ('Ligero'::character varying)::text, ('Otro'::character varying)::text]))),
    CONSTRAINT aircraft_model_power_source_default_check CHECK (((power_source_default)::text = ANY (ARRAY[('ELECTRIC'::character varying)::text, ('NON_ELECTRIC'::character varying)::text]))),
    CONSTRAINT aircraft_model_power_source_type_default_check CHECK (((power_source_type_default)::text = ANY (ARRAY[('HYDROGEN'::character varying)::text, ('GASOLINE'::character varying)::text, ('OTHERS'::character varying)::text])))
);


ALTER TABLE public.aircraft_model OWNER TO admin;

--
-- Name: aircraft_model_documentation; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.aircraft_model_documentation (
    aircraft_model_documentation_id bigint NOT NULL,
    date_indefinite boolean,
    documentation_name character varying(255),
    documentation_type character varying(255),
    expire_date date,
    aircraft_model_id bigint NOT NULL
);


ALTER TABLE public.aircraft_model_documentation OWNER TO admin;

--
-- Name: aircraft_model_documentation_aircraft_model_documentation_i_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.aircraft_model_documentation ALTER COLUMN aircraft_model_documentation_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.aircraft_model_documentation_aircraft_model_documentation_i_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: aircraft_model_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.aircraft_model ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.aircraft_model_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: anexo4; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.anexo4 (
    aplica_modelo boolean,
    calcula_areayevalua_riesgo boolean,
    comunicacion_ministerio_interior boolean,
    conopsymodelo_semantico boolean,
    coords character varying(255),
    cumple_condiciones boolean,
    cumplen_distancias_edificios boolean,
    define_geografia_vuelo_conops boolean,
    define_margen_riesgo_tierra boolean,
    define_vol_contigencia boolean,
    define_zona_terrestre_controlada boolean,
    descripcion character varying(255),
    direccion character varying(255),
    dispone_coord_gestor boolean,
    distancia_minima_infraestructuras boolean,
    entorno_aerodromos boolean,
    entornos_urbanos boolean,
    espacio_aereo_controlado boolean,
    estudio_aeronautico_coordinado boolean,
    fecha_hora_prevista timestamp(6) without time zone,
    imagen_espacio_aereo character varying(255),
    imagen_zona_vuelo character varying(255),
    medios_materiales character varying(255),
    notams boolean,
    otras_limitaciones_inicial boolean,
    otras_limitaciones_valor character varying(255),
    permiso_cecaf boolean,
    permiso_previo_seguridad boolean,
    permiso_previo_servicios boolean,
    personal character varying(255),
    planifica_ubicacion_observadores boolean,
    revisa_notams boolean,
    servicios_esenciales_comunidad boolean,
    tsaocondicionada boolean,
    zona_res_vuelo_fotografico boolean,
    zonas_prohibidas_flexible boolean,
    zonas_prot_medioambiental boolean,
    zonas_seguridad boolean,
    id bigint NOT NULL
);


ALTER TABLE public.anexo4 OWNER TO admin;

--
-- Name: anexo4_aircraft_ids; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.anexo4_aircraft_ids (
    anexo4_id bigint NOT NULL,
    aircraft_id bigint
);


ALTER TABLE public.anexo4_aircraft_ids OWNER TO admin;

--
-- Name: anexo4_otras_limitaciones; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.anexo4_otras_limitaciones (
    anexo4_id bigint NOT NULL,
    descripcion character varying(500),
    valor character varying(50),
    indice integer NOT NULL
);


ALTER TABLE public.anexo4_otras_limitaciones OWNER TO admin;

--
-- Name: anexo5; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.anexo5 (
    analisis_en_funcion_conops boolean,
    atenuacionesarc boolean,
    atenuacionesgrc boolean,
    comprobaciones_uas_vuelo boolean,
    comunicacion3_partes boolean,
    comunicacion_entre_personal boolean,
    condicionantes_acordados_con_gestor boolean,
    condiciones_climatologicas boolean,
    evaluacion_entorno_aereo_adyacente boolean,
    evaluacion_visibilidadyalcance boolean,
    fecha_op timestamp(6) without time zone,
    nombre_conops character varying(255),
    notam_activos boolean,
    personal_sabe_funciones boolean,
    procedimientosatsp boolean,
    requisitos_locales_especificos boolean,
    requisitos_medio_ambiente boolean,
    requisitos_radioelectrico boolean,
    requisitos_seguridad boolean,
    tsa_previa_notam boolean,
    ubicacion_observadores boolean,
    vlos boolean,
    vuelo_terrestre_controlado boolean,
    id bigint NOT NULL
);


ALTER TABLE public.anexo5 OWNER TO admin;

--
-- Name: anexo5_signed_users; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.anexo5_signed_users (
    anexo5_id bigint NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.anexo5_signed_users OWNER TO admin;

--
-- Name: anexo6; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.anexo6 (
    aircraft_id bigint,
    antenas_instaladasyorientadas boolean,
    bateria_carga boolean,
    cableado boolean,
    calibracion boolean,
    calidad_onda boolean,
    centro_gravedad boolean,
    colocacion_correcta boolean,
    conexiones_carga_pago boolean,
    datos_cargados boolean,
    fecha_op timestamp(6) without time zone,
    fijacion_correcta boolean,
    fuente_alimentacion boolean,
    giran_libremente boolean,
    informacion_actualizada boolean,
    integridad_estructural boolean,
    memoria_suficiente_para_datos boolean,
    movimiento_fluido_mando boolean,
    movimiento_fluido_partes_moviles boolean,
    nivel_fuente_alimentacion boolean,
    nombre_conops character varying(255),
    recepcion_adecuada boolean,
    sentido_giro_correcto boolean,
    sin_impacto boolean,
    sin_impacto_carga_pago boolean,
    sin_impacto_helices boolean,
    sin_impacto_motores boolean,
    sin_impacto_partes_moviles boolean,
    sistema_activado boolean,
    sujetacion_firme boolean,
    transmision_datos boolean,
    validar_salida_datos boolean,
    verificacion_luces boolean,
    id bigint NOT NULL
);


ALTER TABLE public.anexo6 OWNER TO admin;

--
-- Name: anexo6_elementos_auxiliares; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.anexo6_elementos_auxiliares (
    anexo6_id bigint NOT NULL,
    descripcion character varying(500),
    valor character varying(50),
    indice integer NOT NULL
);


ALTER TABLE public.anexo6_elementos_auxiliares OWNER TO admin;

--
-- Name: anexo6_materiales_auxiliares; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.anexo6_materiales_auxiliares (
    anexo6_id bigint NOT NULL,
    material_auxiliar character varying(255)
);


ALTER TABLE public.anexo6_materiales_auxiliares OWNER TO admin;

--
-- Name: anexo7; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.anexo7 (
    aeronave_correcto boolean,
    aeronave_observaciones text,
    aircraft_id bigint,
    antenas_correcto boolean,
    antenas_observaciones text,
    baterias_correcto boolean,
    baterias_observaciones text,
    carga_pago_correcto boolean,
    carga_pago_observaciones text,
    ciclos_aterrizaje integer,
    comunicaciones_correcto boolean,
    comunicaciones_observaciones text,
    datos_vuelo_correcto boolean,
    datos_vuelo_observaciones text,
    estructura_correcto boolean,
    estructura_observaciones text,
    fecha_op timestamp(6) without time zone,
    helices_correcto boolean,
    helices_observaciones text,
    identificacion_remota_correcto boolean,
    identificacion_remota_observaciones text,
    motores_correcto boolean,
    motores_observaciones text,
    nombre_conops character varying(255),
    otros_recogida_correcto boolean,
    otros_recogida_observaciones text,
    otros_verificacion_correcto boolean,
    otros_verificacion_observaciones text,
    partes_moviles_correcto boolean,
    partes_moviles_observaciones text,
    planta_potencia_correcto boolean,
    planta_potencia_observaciones text,
    sensores_correcto boolean,
    sensores_observaciones text,
    sensores_recogida_correcto boolean,
    sensores_recogida_observaciones text,
    sistema_geoconsciencia_correcto boolean,
    sistema_geoconsciencia_observaciones text,
    tiempo_vuelo_minutos integer,
    unidad_control_correcto boolean,
    unidad_control_observaciones text,
    id bigint NOT NULL
);


ALTER TABLE public.anexo7 OWNER TO admin;

--
-- Name: anexo8; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.anexo8 (
    anotacion_eventos_ocurridos_operacion boolean,
    anotaciontiempo_actividad_personal boolean,
    anotacion_tiempo_vuelo_aeronave boolean,
    comunicacion3_finalizacion_operacion boolean,
    comunicacion_incidentes boolean,
    comunicacion_zrvf_cecaf boolean,
    condicionesatsp boolean,
    fecha_op timestamp(6) without time zone,
    nombre_conops character varying(255),
    id bigint NOT NULL
);


ALTER TABLE public.anexo8 OWNER TO admin;

--
-- Name: anexo8_otras_limitaciones; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.anexo8_otras_limitaciones (
    anexo8_id bigint NOT NULL,
    descripcion character varying(500),
    valor character varying(50),
    indice integer NOT NULL
);


ALTER TABLE public.anexo8_otras_limitaciones OWNER TO admin;

--
-- Name: anexos_base; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.anexos_base (
    id bigint NOT NULL,
    estado character varying(20) NOT NULL,
    fecha_firma timestamp(6) without time zone,
    firmado_por character varying(255),
    numero_version integer NOT NULL,
    tipo_anexo integer,
    id_operacion bigint NOT NULL,
    CONSTRAINT anexos_base_estado_check CHECK (((estado)::text = ANY (ARRAY[('BORRADOR'::character varying)::text, ('FIRMADO'::character varying)::text])))
);


ALTER TABLE public.anexos_base OWNER TO admin;

--
-- Name: anexos_base_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.anexos_base ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.anexos_base_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_user; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.app_user (
    user_id integer NOT NULL,
    doc_identidad character varying(120) NOT NULL,
    email character varying(120) NOT NULL,
    fecha_nac date,
    first_name character varying(100) NOT NULL,
    image_path character varying(255),
    last_name character varying(150) NOT NULL,
    password_hash character varying(255) NOT NULL,
    phone_number integer,
    state boolean NOT NULL,
    username character varying(80) NOT NULL
);


ALTER TABLE public.app_user OWNER TO admin;

--
-- Name: app_user_roles; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.app_user_roles (
    user_id integer NOT NULL,
    role character varying(50) NOT NULL,
    CONSTRAINT app_user_roles_role_check CHECK (((role)::text = ANY (ARRAY[('ADMIN'::character varying)::text, ('MANAGER'::character varying)::text, ('MAINTAINER'::character varying)::text, ('PILOT'::character varying)::text])))
);


ALTER TABLE public.app_user_roles OWNER TO admin;

--
-- Name: app_user_user_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.app_user ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_user_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: automatic_mail_preference; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.automatic_mail_preference (
    automatic_mail_preference_id bigint NOT NULL,
    certificates_enabled boolean NOT NULL,
    events_enabled boolean NOT NULL,
    maintenance_enabled boolean NOT NULL,
    operations_enabled boolean NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.automatic_mail_preference OWNER TO admin;

--
-- Name: automatic_mail_preference_automatic_mail_preference_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.automatic_mail_preference ALTER COLUMN automatic_mail_preference_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.automatic_mail_preference_automatic_mail_preference_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: backup_settings; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.backup_settings (
    backup_settings_id integer NOT NULL,
    last_backup_path character varying(255),
    last_run_date date,
    schedule_day integer NOT NULL,
    schedule_hour integer NOT NULL
);


ALTER TABLE public.backup_settings OWNER TO admin;

--
-- Name: document_versions; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.document_versions (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    file_url character varying(1024) NOT NULL,
    revision_number integer NOT NULL,
    upload_notes character varying(2048),
    version_number integer NOT NULL,
    documentation_id bigint NOT NULL
);


ALTER TABLE public.document_versions OWNER TO admin;

--
-- Name: document_versions_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.document_versions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.document_versions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: extra_date; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.extra_date (
    id_extra_date bigint NOT NULL,
    description character varying(255),
    extra_date date NOT NULL
);


ALTER TABLE public.extra_date OWNER TO admin;

--
-- Name: extra_date_id_extra_date_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.extra_date ALTER COLUMN id_extra_date ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.extra_date_id_extra_date_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: extra_date_roles; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.extra_date_roles (
    extra_date_id bigint NOT NULL,
    role_name character varying(255)
);


ALTER TABLE public.extra_date_roles OWNER TO admin;

--
-- Name: flight_time; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.flight_time (
    flight_time_id bigint NOT NULL,
    aircraft_manufacturer character varying(255),
    aircraft_model character varying(255),
    aircraft_serial_number character varying(255),
    comments character varying(2000),
    duration_minutes integer NOT NULL,
    flight_date date NOT NULL,
    total_flight_time_minutes integer NOT NULL,
    aircraft_id bigint NOT NULL,
    operation_id bigint,
    operation_code character varying(50)
);


ALTER TABLE public.flight_time OWNER TO admin;

--
-- Name: flight_time_documentation; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.flight_time_documentation (
    id bigint NOT NULL,
    date_indefinite boolean,
    documentation_name character varying(255),
    documentation_type character varying(255),
    expire_date date,
    file_path character varying(255),
    flight_time_id bigint NOT NULL
);


ALTER TABLE public.flight_time_documentation OWNER TO admin;

--
-- Name: flight_time_documentation_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.flight_time_documentation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.flight_time_documentation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: flight_time_flight_time_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.flight_time ALTER COLUMN flight_time_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.flight_time_flight_time_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: maintenance; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.maintenance (
    maintenance_id bigint NOT NULL,
    comments character varying(500),
    hours_flight_required integer NOT NULL,
    maintenance_date date NOT NULL,
    months_required integer NOT NULL,
    next_maintenance_date date,
    review_type character varying(255) NOT NULL,
    aircraft_id bigint NOT NULL
);


ALTER TABLE public.maintenance OWNER TO admin;

--
-- Name: maintenance_documentation; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.maintenance_documentation (
    id bigint NOT NULL,
    date_indefinite boolean,
    documentation_name character varying(255),
    documentation_type character varying(255),
    expire_date date,
    file_path character varying(255),
    maintenance_id bigint NOT NULL
);


ALTER TABLE public.maintenance_documentation OWNER TO admin;

--
-- Name: maintenance_documentation_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.maintenance_documentation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.maintenance_documentation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: maintenance_maintenance_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.maintenance ALTER COLUMN maintenance_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.maintenance_maintenance_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notification_settings; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.notification_settings (
    notification_settings_id integer NOT NULL,
    certificate_first_days_ahead integer NOT NULL,
    certificate_second_days_ahead integer NOT NULL,
    event_days_ahead integer NOT NULL,
    last_run_date date,
    maintenance_days_ahead integer NOT NULL,
    operation_days_ahead integer NOT NULL,
    schedule_hour integer NOT NULL,
    schedule_minute integer NOT NULL
);


ALTER TABLE public.notification_settings OWNER TO admin;

--
-- Name: operation; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.operation (
    id_operacion bigint NOT NULL,
    anio_correlativo integer NOT NULL,
    codigo character varying(20) NOT NULL,
    conops character varying(255),
    correlativo_anual integer NOT NULL,
    estado character varying(20) NOT NULL,
    fecha_actualizacion timestamp(6) without time zone,
    fecha_creacion timestamp(6) without time zone NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT operation_estado_check CHECK (((estado)::text = ANY (ARRAY[('CANCELADA'::character varying)::text, ('EN_CURSO'::character varying)::text, ('PENDIENTE'::character varying)::text, ('COMPLETADA'::character varying)::text])))
);


ALTER TABLE public.operation OWNER TO admin;

--
-- Name: operation_assigned_users; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.operation_assigned_users (
    operation_id bigint NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.operation_assigned_users OWNER TO admin;

--
-- Name: operation_documentation; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.operation_documentation (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.operation_documentation OWNER TO admin;

--
-- Name: operation_documentation_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.operation_documentation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.operation_documentation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: operation_id_operacion_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.operation ALTER COLUMN id_operacion ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.operation_id_operacion_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: personalExterno; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."personalExterno" (
    anexo4_id bigint NOT NULL,
    nombre_apellidos character varying(255),
    rol character varying(255),
    indice integer NOT NULL
);


ALTER TABLE public."personalExterno" OWNER TO admin;

--
-- Name: sent_mail; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.sent_mail (
    sent_mail_id bigint NOT NULL,
    header character varying(180) NOT NULL,
    recipient_mode character varying(20) NOT NULL,
    sent_at timestamp(6) without time zone NOT NULL,
    body_text text NOT NULL,
    sender_username character varying(80) NOT NULL
);


ALTER TABLE public.sent_mail OWNER TO admin;

--
-- Name: sent_mail_recipients; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.sent_mail_recipients (
    sent_mail_id bigint NOT NULL,
    recipient character varying(140) NOT NULL
);


ALTER TABLE public.sent_mail_recipients OWNER TO admin;

--
-- Name: sent_mail_selected_roles; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.sent_mail_selected_roles (
    sent_mail_id bigint NOT NULL,
    role character varying(50) NOT NULL,
    CONSTRAINT sent_mail_selected_roles_role_check CHECK (((role)::text = ANY (ARRAY[('ADMIN'::character varying)::text, ('MANAGER'::character varying)::text, ('MAINTAINER'::character varying)::text, ('PILOT'::character varying)::text])))
);


ALTER TABLE public.sent_mail_selected_roles OWNER TO admin;

--
-- Name: sent_mail_selected_users; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.sent_mail_selected_users (
    sent_mail_id bigint NOT NULL,
    username character varying(80) NOT NULL
);


ALTER TABLE public.sent_mail_selected_users OWNER TO admin;

--
-- Name: sent_mail_sent_mail_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.sent_mail ALTER COLUMN sent_mail_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sent_mail_sent_mail_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_certificate; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.user_certificate (
    user_certificate_id integer NOT NULL,
    certificate_name character varying(255),
    certificate_type character varying(255),
    date_indefinite boolean,
    expire_date date,
    user_id integer NOT NULL
);


ALTER TABLE public.user_certificate OWNER TO admin;

--
-- Name: user_certificate_user_certificate_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.user_certificate ALTER COLUMN user_certificate_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_certificate_user_certificate_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: aircraft; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.aircraft (aircraft_id, accessories, class, cautive, config, fecha_fab, flight_minutes, camera, has_ensurance, has_fts, has_parachute, image_path, impact_energy, max_speed, mtom, power_source, power_source_type, privately_built, serial_number, wingspan, aircraft_model_id, max_autonomy, observations) FROM stdin;
2	- Luces de navegación / control / anticolisión (opcional) - Foco (opcional) - Tirada de línea guía (opcional) - Paracaídas balístico (opcional) - FTS (opcional) - Gimbal con cámara giroestabilizada RGB/IR	No	NO	Multirrotor	\N	7670	t	\N	t	f	database-relationed/aircraft-model/Condor-Dronetools_S_L_/profile/aircraft_model_17_profile.png	850.000	10.000	14.900	1	\N	f	DTCON001	1.950	17	180.000	\N
5	- Luces de navegación / control / anticolisión (opcional)\r\n- Paracaídas balístico (opcional)\r\n- FTS (opcional)\r\n- Gimbal con cámara giroestabilizada RGB/IR	No	NO	Multirrotor	\N	60	t	\N	f	f	database-relationed/aircraft-model/Benceno-Dronetools_S_L_/profile/aircraft_model_18_profile.png	913.000	21.000	19.000	\N	1	f	16089DTE522001	2.400	18	180.000	\N
6	\N	C0	\N	Avion	\N	240	f	\N	\N	\N	\N	13.000	13.000	13.000	0	\N	\N	FDASFDSAFDASFDSA	13.000	22	\N	\N
\.


--
-- Data for Name: aircraft_documentation; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.aircraft_documentation (aircraft_documentation_id, date_indefinite, documentation_name, documentation_type, expire_date, aircraft_id, aircraft_model_documentation_id) FROM stdin;
1	f	database-relationed/aircraft/DTCON001-Condor/documentation/caracterizacion/2-caracterizacion-Caracterizacion_UAS_Condor_DTCON001_docx.pdf	caracterizacion	\N	2	\N
6	\N	\N	manualMantenimiento	\N	5	13
7	\N	\N	manualUsuario	\N	5	14
2	\N	\N	manualUsuario	\N	2	\N
4	\N	\N	manualMantenimiento	\N	2	\N
3	f	\N	manualUsuarioFTS	\N	2	11
5	f	\N	documentoTecnicoFTS	\N	2	12
8	\N	\N	fdsafdsafdasfds	\N	6	\N
9	f	database-relationed/aircraft/FDASFDSAFDASFDSA-prueba/documentation/manualMantenimiento/6-manualMantenimiento-21mb.pdf	manualMantenimiento	\N	6	\N
\.


--
-- Data for Name: aircraft_model; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.aircraft_model (id, accessories_default, aircraft_class_default, cautive_default, config_default, has_camera_default, has_fts_default, has_parachute_default, image_path, impact_energy_default, manufacturer, max_speed_default, model, mtom_default, power_source_default, power_source_type_default, privately_built_default, wingspan_default, max_autonomy_default, observations_default) FROM stdin;
7	Opciones disponibles: - Altavoces - Luces de navegación/ de control/ anticolisión - Megáfono - Balizado - Paracaídas balístico - Suelta - Antorcha - Tirada de línea guía - Gimbal con cámara giroestabilizada RGB/IR - Depósito  - Fumigador velutina	No	NO	Multirrotor	t	f	f	database-relationed/aircraft-model/Droneocto_8-Dronetools_S_L_/profile/aircraft_model_7_profile.png	783.000	Dronetools S.L.	11.000	Droneocto 8	9.900	ELECTRIC	\N	f	1.350	25.000	\N
3	Opciones disponibles: - Luces de navegación/ de control/ anticolisión - Gimbal con cámara giroestabilizada RGB/IR	No	NO	Avion	t	f	f	database-relationed/aircraft-model/Passer-Dronetools_S_L_/profile/aircraft_model_3_profile.png	2160.000	Dronetools S.L.	30.000	Passer	4.800	ELECTRIC	\N	f	2.200	120.000	\N
2	\N	No	NO	Multirrotor	t	f	f	database-relationed/aircraft-model/Signage-Dronetools_S_L_/profile/aircraft_model_2_profile.png	359.000	Dronetools S.L.	10.000	Signage	7.500	ELECTRIC	\N	f	1.510	25.000	\N
6	Opciones disponibles: - Altavoces - Luces de navegación/ de control/ anticolisión - Megáfono - Balizado - Paracaídas balístico - Suelta - Antorcha - Tirada de línea guía - Gimbal con cámara giroestabilizada RGB/IR	No	NO	Multirrotor	t	f	\N	database-relationed/aircraft-model/Dronequad_4-Dronetools_S_L_/profile/aircraft_model_6_profile.png	243.000	Dronetools S.L.	10.000	Dronequad 4	3.800	ELECTRIC	\N	f	0.930	20.000	\N
5	Opciones disponibles: - Altavoces - Luces de navegación/ de control/ anticolisión - Megáfono - Balizado - Paracaídas balístico - Suelta - Antorcha - Tirada de línea guía - Gimbal con cámara giroestabilizada RGB/IR - Depósito  - Fumigador velutina	No	NO	Multirrotor	t	f	f	database-relationed/aircraft-model/Inspector-Dronetools_S_L_/profile/aircraft_model_5_profile.png	850.000	Dronetools S.L.	10.000	Inspector	14.900	ELECTRIC	\N	f	1.950	60.000	\N
4	Opciones disponibles: - Altavoces - Luces de navegación/ de control/ anticolisión - Megáfono - Balizado - Paracaídas balístico - Suelta - Antorcha - Tirada de línea guía - Gimbal con cámara giroestabilizada RGB/IR	No	NO	Multirrotor	t	f	f	database-relationed/aircraft-model/Minicondor-Dronetools_S_L_/profile/aircraft_model_4_profile.png	422.000	Dronetools S.L.	9.000	Minicondor	7.000	ELECTRIC	\N	f	1.300	50.000	\N
18	- Luces de navegación / control / anticolisión (opcional)\r\n- Paracaídas balístico (opcional)\r\n- FTS (opcional)\r\n- Gimbal con cámara giroestabilizada RGB/IR	No	NO	Multirrotor	t	f	f	database-relationed/aircraft-model/Benceno-Dronetools_S_L_/profile/aircraft_model_18_profile.png	913.000	Dronetools S.L.	21.000	Benceno	19.000	NON_ELECTRIC	GASOLINE	f	2.400	180.000	\N
8	- Luces de navegación / control / anticolisión (opcional)\r\n- Paracaídas balístico (opcional)\r\n- FTS (opcional)\r\n- Gimbal con cámara giroestabilizada RGB/IR	No	NO	\N	t	t	f	database-relationed/aircraft-model/AZOR_A22__PASSER_330_E-Dronetools_S_L_/profile/aircraft_model_8_profile.png	9728.000	Dronetools S.L.	32.000	AZOR A22-PASSER 330 E	19.000	ELECTRIC	\N	\N	3.300	90.000	probando
12	Opciones disponibles: - Altavoces - Luces de navegación/ de control/ anticolisión - Megáfono - Balizado - Paracaídas balístico - Suelta - Antorcha - Tirada de línea guía - Gimbal con cámara giroestabilizada RGB/IR - Depósito  - Fumigador velutina	No	NO	Multirrotor	t	f	\N	database-relationed/aircraft-model/Dronehexa_6-Dronetools_S_L_/profile/aircraft_model_12_profile.png	568.000	Dronetools S.L.	10.000	Dronehexa 6	7.500	ELECTRIC	\N	f	1.200	30.000	\N
11	Depósito de 10 litros con un sistema de rocioado/pulverizado de líquido automático.	No	NO	Multirrotor	t	f	\N	database-relationed/aircraft-model/Dronehexa_AG-Dronetools_S_L_/profile/aircraft_model_11_profile.png	1865.000	Dronetools S.L.	10.000	Dronehexa AG	24.900	ELECTRIC	\N	f	2.200	18.000	\N
10	Depósito de 16 litros con un sistema de rocioado/pulverizado de líquido automático.	No	NO	Multirrotor	t	f	f	database-relationed/aircraft-model/Dronehexa_AG16_XL-Dronetools_S_L_/profile/aircraft_model_10_profile.png	5308.000	Dronetools S.L.	13.000	Dronehexa AG16 XL	42.000	ELECTRIC	\N	f	2.200	15.000	\N
9	Opciones disponibles: - Altavoces - Luces de navegación/ de control/ anticolisión - Megáfono - Balizado - Paracaídas balístico - Suelta - Antorcha - Tirada de línea guía - Gimbal con cámara giroestabilizada RGB/IR - Depósito  - Fumigador velutina	No	NO	Multirrotor	t	f	f	database-relationed/aircraft-model/Dronehexa_XL-Dronetools_S_L_/profile/aircraft_model_9_profile.png	1865.000	Dronetools S.L.	10.000	Dronehexa XL	24.900	ELECTRIC	\N	f	2.200	18.000	\N
14	Opciones disponibles: - Altavoces - Luces de navegación/ de control/ anticolisión - Megáfono - Balizado - Paracaídas balístico - Suelta - Antorcha - Tirada de línea guía - Gimbal con cámara giroestabilizada RGB/IR	No	NO	Multirrotor	t	f	f	database-relationed/aircraft-model/Dron_Tesla-Dronetools_S_L_/profile/aircraft_model_14_profile.jpg	206.000	Dronetools S.L.	9.000	Dron Tesla	3.900	ELECTRIC	\N	f	1.035	25.000	\N
13	Opciones disponibles: - Altavoces - Luces de navegación/ de control/ anticolisión - Megáfono - Balizado - Paracaídas balístico - Suelta - Antorcha - Tirada de línea guía - Gimbal con cámara giroestabilizada RGB/IR - Depósito  - Fumigador velutina	No	NO	Multirrotor	t	f	f	database-relationed/aircraft-model/Drone_Quasar-Dronetools_S_L_/profile/aircraft_model_13_profile.png	309.000	Dronetools S.L.	7.000	Drone Quasar	8.300	ELECTRIC	\N	f	1.800	60.000	\N
17	- Luces de navegación / control / anticolisión (opcional) - Foco (opcional) - Tirada de línea guía (opcional) - Paracaídas balístico (opcional) - FTS (opcional) - Gimbal con cámara giroestabilizada RGB/IR	No	NO	Multirrotor	t	t	f	database-relationed/aircraft-model/Condor-Dronetools_S_L_/profile/aircraft_model_17_profile.png	850.000	Dronetools S.L.	10.000	Condor	14.900	ELECTRIC	\N	f	1.950	60.000	\N
15	Luces de navegación/SONAR/Gimbal Colgante/flotadores	No	NO	Multirrotor	t	f	f	database-relationed/aircraft-model/Cormorant-Dronetools_S_L_/profile/aircraft_model_15_profile.jpg	865.000	Dronetools S.L.	5.000	Cormorant	17.500	ELECTRIC	\N	f	2.270	45.000	Tiene la capacidad de amenizar sobre el agua y desplazarse con propulsión propia
16	- Luces de navegación / control / anticolisión (opcional)\r\n- Paracaídas balístico (opcional)\r\n- FTS (opcional)\r\n- Gimbal con cámara giroestabilizada RGB/IR	No	NO	Hibrido_vtol	t	t	f	database-relationed/aircraft-model/AZOR_A22__PASSER_330_H-Dronetools_S_L_/profile/aircraft_model_16_profile.png	11520.000	Dronetools S.L.	32.000	AZOR A22/ PASSER 330 H	22.500	NON_ELECTRIC	\N	f	3.300	240.000	\N
19	- Luces de navegación / control / anticolisión (opcional)\r\n- Paracaídas balístico (opcional)\r\n- FTS (opcional)\r\n- Gimbal con cámara giroestabilizada RGB/IR	No	NO	Hibrido_vtol	t	t	f	database-relationed/aircraft-model/AZOR_A24-Dronetools_S_L_/profile/aircraft_model_19_profile.png	6228.000	Dronetools S.L.	30.000	AZOR A24	13.840	ELECTRIC	\N	f	1.300	30.000	\N
22	\N	\N	\N	\N	\N	\N	\N	\N	\N	prueba	\N	prueba	\N	\N	\N	\N	\N	\N	\N
20	\N	\N	\N	\N	\N	\N	\N	\N	\N	DJI	\N	Matrice 4T	\N	NON_ELECTRIC	\N	\N	\N	\N	\N
\.


--
-- Data for Name: aircraft_model_documentation; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.aircraft_model_documentation (aircraft_model_documentation_id, date_indefinite, documentation_name, documentation_type, expire_date, aircraft_model_id) FROM stdin;
1	f	database-relationed/aircraft-model/AZOR_A22__PASSER_330_E-Dronetools_S_L_/documentation/manualUsuario/8-manualUsuario-Manual_de_usuario_Azor_A22_Passer_330_El_ctrico_V_2.pdf	manualUsuario	\N	8
2	f	database-relationed/aircraft-model/AZOR_A22__PASSER_330_E-Dronetools_S_L_/documentation/manualMantenimiento/8-manualMantenimiento-Manual_de_mantenimiento_fabricante_AZOR_A22_El_ctrico_Rev_03-1.pdf	manualMantenimiento	\N	8
3	f	database-relationed/aircraft-model/AZOR_A22__PASSER_330_E-Dronetools_S_L_/documentation/manualUsuarioFTS/8-manualUsuarioFTS-Manual_de_Uso_del_Sistema_de_Terminaci_n_de_Vuelo__FTS__AZOR_V2.pdf	manualUsuarioFTS	\N	8
4	f	database-relationed/aircraft-model/AZOR_A22__PASSER_330_E-Dronetools_S_L_/documentation/documentoTecnicoFTS/8-documentoTecnicoFTS-Documento_t_cnico_Sistema_de_Terminaci_n_de_Vuelo__FTS__Azor.pdf	documentoTecnicoFTS	\N	8
11	f	database-relationed/aircraft-model/Condor-Dronetools_S_L_/documentation/manualUsuarioFTS/17-manualUsuarioFTS-Manual_de_Uso_del_Sistema_de_Terminaci_n_de_Vuelo__FTS__V2.pdf	manualUsuarioFTS	\N	17
12	f	database-relationed/aircraft-model/Condor-Dronetools_S_L_/documentation/documentoTecnicoFTS/17-documentoTecnicoFTS-Documento_t_cnico_Sistema_de_Terminaci_n_de_Vuelo__FTS__C_ndor.pdf	documentoTecnicoFTS	\N	17
13	f	database-relationed/aircraft-model/Benceno-Dronetools_S_L_/documentation/manualMantenimiento/18-manualMantenimiento-Manual_de_mantenimiento_Benceno_V_03_docx.pdf	manualMantenimiento	\N	18
14	f	database-relationed/aircraft-model/Benceno-Dronetools_S_L_/documentation/manualUsuario/18-manualUsuario-Manual_de_usuario_BENCENO_V_4_docx.pdf	manualUsuario	\N	18
15	f	database-relationed/aircraft-model/AZOR_A24-Dronetools_S_L_/documentation/manualUsuario/19-manualUsuario-Manual_de_usuario_Azor_A24_V_2_docx.pdf	manualUsuario	\N	19
16	f	database-relationed/aircraft-model/AZOR_A24-Dronetools_S_L_/documentation/manualMantenimiento/19-manualMantenimiento-Manual_de_mantenimiento_fabricante_AZOR_A24_Rev_01_docx-1.pdf	manualMantenimiento	\N	19
18	f	database-relationed/aircraft-model/AZOR_A24-Dronetools_S_L_/documentation/documentoTecnicoFTS/19-documentoTecnicoFTS-Documento_t_cnico_Sistema_de_Terminaci_n_de_Vuelo__FTS__Azor_A24-1.pdf	documentoTecnicoFTS	\N	19
17	f	database-relationed/aircraft-model/AZOR_A24-Dronetools_S_L_/documentation/manualUsuarioFTS/19-manualUsuarioFTS-Manual_de_Uso_del_Sistema_de_Terminaci_n_de_Vuelo__FTS__AZOR_A24-1.pdf	manualUsuarioFTS	\N	19
5	f	database-relationed/aircraft-model/AZOR_A22__PASSER_330_H-Dronetools_S_L_/documentation/manualUsuario/16-manualUsuario-Manual_de_usuario_Azor_A22_Passer_330_H_brido_V_2.pdf	manualUsuario	\N	16
8	f	database-relationed/aircraft-model/AZOR_A22__PASSER_330_H-Dronetools_S_L_/documentation/documentoTecnicoFTS/16-documentoTecnicoFTS-Documento_t_cnico_Sistema_de_Terminaci_n_de_Vuelo__FTS__Azor.pdf	documentoTecnicoFTS	\N	16
7	f	database-relationed/aircraft-model/AZOR_A22__PASSER_330_H-Dronetools_S_L_/documentation/manualUsuarioFTS/16-manualUsuarioFTS-Manual_de_Uso_del_Sistema_de_Terminaci_n_de_Vuelo__FTS__AZOR_V2.pdf	manualUsuarioFTS	\N	16
6	f	database-relationed/aircraft-model/AZOR_A22__PASSER_330_H-Dronetools_S_L_/documentation/manualMantenimiento/16-manualMantenimiento-Manual_de_mantenimiento_fabricante_AZOR_A22_El_ctrico_Rev_03-1.pdf	manualMantenimiento	\N	16
19	f	database-relationed/aircraft-model/Matrice_4T-DJI/documentation/manualUsuario/20-manualUsuario-19mb.pdf	manualUsuario	\N	20
20	f	database-relationed/aircraft-model/Condor-Dronetools_S_L_/documentation/manualMantenimiento/17-manualMantenimiento-19mb.pdf	manualMantenimiento	\N	17
21	f	database-relationed/aircraft-model/Matrice_4T-DJI/documentation/manualMantenimiento/20-manualMantenimiento-21mb.pdf	manualMantenimiento	\N	20
\.


--
-- Data for Name: anexo4; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.anexo4 (aplica_modelo, calcula_areayevalua_riesgo, comunicacion_ministerio_interior, conopsymodelo_semantico, coords, cumple_condiciones, cumplen_distancias_edificios, define_geografia_vuelo_conops, define_margen_riesgo_tierra, define_vol_contigencia, define_zona_terrestre_controlada, descripcion, direccion, dispone_coord_gestor, distancia_minima_infraestructuras, entorno_aerodromos, entornos_urbanos, espacio_aereo_controlado, estudio_aeronautico_coordinado, fecha_hora_prevista, imagen_espacio_aereo, imagen_zona_vuelo, medios_materiales, notams, otras_limitaciones_inicial, otras_limitaciones_valor, permiso_cecaf, permiso_previo_seguridad, permiso_previo_servicios, personal, planifica_ubicacion_observadores, revisa_notams, servicios_esenciales_comunidad, tsaocondicionada, zona_res_vuelo_fotografico, zonas_prohibidas_flexible, zonas_prot_medioambiental, zonas_seguridad, id) FROM stdin;
\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	N/A	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	3
\.


--
-- Data for Name: anexo4_aircraft_ids; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.anexo4_aircraft_ids (anexo4_id, aircraft_id) FROM stdin;
\.


--
-- Data for Name: anexo4_otras_limitaciones; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.anexo4_otras_limitaciones (anexo4_id, descripcion, valor, indice) FROM stdin;
\.


--
-- Data for Name: anexo5; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.anexo5 (analisis_en_funcion_conops, atenuacionesarc, atenuacionesgrc, comprobaciones_uas_vuelo, comunicacion3_partes, comunicacion_entre_personal, condicionantes_acordados_con_gestor, condiciones_climatologicas, evaluacion_entorno_aereo_adyacente, evaluacion_visibilidadyalcance, fecha_op, nombre_conops, notam_activos, personal_sabe_funciones, procedimientosatsp, requisitos_locales_especificos, requisitos_medio_ambiente, requisitos_radioelectrico, requisitos_seguridad, tsa_previa_notam, ubicacion_observadores, vlos, vuelo_terrestre_controlado, id) FROM stdin;
\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N		\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	4
\.


--
-- Data for Name: anexo5_signed_users; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.anexo5_signed_users (anexo5_id, user_id) FROM stdin;
\.


--
-- Data for Name: anexo6; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.anexo6 (aircraft_id, antenas_instaladasyorientadas, bateria_carga, cableado, calibracion, calidad_onda, centro_gravedad, colocacion_correcta, conexiones_carga_pago, datos_cargados, fecha_op, fijacion_correcta, fuente_alimentacion, giran_libremente, informacion_actualizada, integridad_estructural, memoria_suficiente_para_datos, movimiento_fluido_mando, movimiento_fluido_partes_moviles, nivel_fuente_alimentacion, nombre_conops, recepcion_adecuada, sentido_giro_correcto, sin_impacto, sin_impacto_carga_pago, sin_impacto_helices, sin_impacto_motores, sin_impacto_partes_moviles, sistema_activado, sujetacion_firme, transmision_datos, validar_salida_datos, verificacion_luces, id) FROM stdin;
\.


--
-- Data for Name: anexo6_elementos_auxiliares; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.anexo6_elementos_auxiliares (anexo6_id, descripcion, valor, indice) FROM stdin;
\.


--
-- Data for Name: anexo6_materiales_auxiliares; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.anexo6_materiales_auxiliares (anexo6_id, material_auxiliar) FROM stdin;
\.


--
-- Data for Name: anexo7; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.anexo7 (aeronave_correcto, aeronave_observaciones, aircraft_id, antenas_correcto, antenas_observaciones, baterias_correcto, baterias_observaciones, carga_pago_correcto, carga_pago_observaciones, ciclos_aterrizaje, comunicaciones_correcto, comunicaciones_observaciones, datos_vuelo_correcto, datos_vuelo_observaciones, estructura_correcto, estructura_observaciones, fecha_op, helices_correcto, helices_observaciones, identificacion_remota_correcto, identificacion_remota_observaciones, motores_correcto, motores_observaciones, nombre_conops, otros_recogida_correcto, otros_recogida_observaciones, otros_verificacion_correcto, otros_verificacion_observaciones, partes_moviles_correcto, partes_moviles_observaciones, planta_potencia_correcto, planta_potencia_observaciones, sensores_correcto, sensores_observaciones, sensores_recogida_correcto, sensores_recogida_observaciones, sistema_geoconsciencia_correcto, sistema_geoconsciencia_observaciones, tiempo_vuelo_minutos, unidad_control_correcto, unidad_control_observaciones, id) FROM stdin;
\.


--
-- Data for Name: anexo8; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.anexo8 (anotacion_eventos_ocurridos_operacion, anotaciontiempo_actividad_personal, anotacion_tiempo_vuelo_aeronave, comunicacion3_finalizacion_operacion, comunicacion_incidentes, comunicacion_zrvf_cecaf, condicionesatsp, fecha_op, nombre_conops, id) FROM stdin;
\.


--
-- Data for Name: anexo8_otras_limitaciones; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.anexo8_otras_limitaciones (anexo8_id, descripcion, valor, indice) FROM stdin;
\.


--
-- Data for Name: anexos_base; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.anexos_base (id, estado, fecha_firma, firmado_por, numero_version, tipo_anexo, id_operacion) FROM stdin;
3	BORRADOR	\N	\N	1	4	7
4	BORRADOR	\N	\N	1	5	7
\.


--
-- Data for Name: app_user; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.app_user (user_id, doc_identidad, email, fecha_nac, first_name, image_path, last_name, password_hash, phone_number, state, username) FROM stdin;
9	00000000T	admin@admin.es	\N	ADMIN	\N	ADMIN	$2b$12$6cdleoSsH9EtO.vo2bT84Ohltj4SthGTl5dZbsV0bDXogVEEXuICS	\N	t	admin
11	4321432143214321412	fdsafdsafdsa@fdasfdsa.es	\N	fasfdsa	\N	fdsafdsafdsa	$2a$10$5LEKULwIz8BRVWUZC24s2eRIxSAnpEDi57SWeQctpH5sJ4vCrZPvS	\N	t	fdsafdsafds
\.


--
-- Data for Name: app_user_roles; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.app_user_roles (user_id, role) FROM stdin;
9	ADMIN
11	PILOT
\.


--
-- Data for Name: automatic_mail_preference; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.automatic_mail_preference (automatic_mail_preference_id, certificates_enabled, events_enabled, maintenance_enabled, operations_enabled, user_id) FROM stdin;
\.


--
-- Data for Name: backup_settings; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.backup_settings (backup_settings_id, last_backup_path, last_run_date, schedule_day, schedule_hour) FROM stdin;
1	/app/backups/2026-05-28	2026-05-28	1	2
\.


--
-- Data for Name: document_versions; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.document_versions (id, created_at, file_url, revision_number, upload_notes, version_number, documentation_id) FROM stdin;
1	2026-06-01 07:27:34.614005	v1_r0_1_dummy_pdf_operation_documentation.pdf	0	fdsafdsafdsa	1	1
2	2026-06-01 08:15:54.38349	v1_r0_2_19mb_operation_documentation.pdf	0	19mb	1	2
5	2026-06-01 08:33:30.286019	v0_r0_5_19mb_operation_documentation.pdf	0		0	5
6	2026-06-01 10:15:04.631691	v1_r0_6_19mb_operation_documentation.pdf	0		1	6
\.


--
-- Data for Name: extra_date; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.extra_date (id_extra_date, description, extra_date) FROM stdin;
\.


--
-- Data for Name: extra_date_roles; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.extra_date_roles (extra_date_id, role_name) FROM stdin;
\.


--
-- Data for Name: flight_time; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.flight_time (flight_time_id, aircraft_manufacturer, aircraft_model, aircraft_serial_number, comments, duration_minutes, flight_date, total_flight_time_minutes, aircraft_id, operation_id, operation_code) FROM stdin;
60	Dronetools S.L.	Benceno	16089DTE522001	\N	60	1212-12-12	60	5	\N	prueba de codigo
62	prueba	prueba	FDASFDSAFDASFDSA	\N	60	4343-03-31	120	6	\N	4444444444444444444
61	prueba	prueba	FDASFDSAFDASFDSA	\N	60	4344-03-31	180	6	\N	999999999999999
63	prueba	prueba	FDASFDSAFDASFDSA	\N	60	4344-03-31	240	6	\N	O-2026-111
65	prueba	prueba	FDASFDSAFDASFDSA	\N	60	1111-11-11	60	6	\N	probando0000000000000
\.


--
-- Data for Name: flight_time_documentation; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.flight_time_documentation (id, date_indefinite, documentation_name, documentation_type, expire_date, file_path, flight_time_id) FROM stdin;
\.


--
-- Data for Name: maintenance; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.maintenance (maintenance_id, comments, hours_flight_required, maintenance_date, months_required, next_maintenance_date, review_type, aircraft_id) FROM stdin;
2	\N	6310	2022-01-17	12	2023-01-09	Inspección básica	2
3	\N	7155	2023-01-09	12	2024-01-11	Inspección general	2
4	\N	7375	2024-01-11	12	2024-12-17	Inspección básica	2
5	\N	8023	2024-12-17	11	2025-12-17	Revisión general	2
6	\N	14595	2025-12-19	12	2026-12-19	Revisión básica	2
8	\N	600	2024-08-14	12	2025-08-14	Inspección general	5
7	\N	250	2023-08-16	12	2024-08-14	Inspección básica	5
\.


--
-- Data for Name: maintenance_documentation; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.maintenance_documentation (id, date_indefinite, documentation_name, documentation_type, expire_date, file_path, maintenance_id) FROM stdin;
2	t	database-relationed/aircraft/DTCON001-Condor/maintenance/2-2022-01-17/maintenance_2_documentacion_de_mantenimiento_Mant_Condor_2022.pdf	Documentacion de mantenimiento	\N	database-relationed/aircraft/DTCON001-Condor/maintenance/2-2022-01-17/maintenance_2_documentacion_de_mantenimiento_Mant_Condor_2022.pdf	2
3	t	database-relationed/aircraft/DTCON001-Condor/maintenance/3-2023-12-09/maintenance_3_documentacion_de_mantenimiento_Mant_Condor_2023.pdf	Documentacion de mantenimiento	\N	database-relationed/aircraft/DTCON001-Condor/maintenance/3-2023-12-09/maintenance_3_documentacion_de_mantenimiento_Mant_Condor_2023.pdf	3
4	t	database-relationed/aircraft/DTCON001-Condor/maintenance/4-2024-01-11/maintenance_4_documentacion_de_mantenimiento_Mant_Condor_2024.pdf	Documentacion de mantenimiento	\N	database-relationed/aircraft/DTCON001-Condor/maintenance/4-2024-01-11/maintenance_4_documentacion_de_mantenimiento_Mant_Condor_2024.pdf	4
5	t	database-relationed/aircraft/DTCON001-Condor/maintenance/5-2024-12-17/maintenance_5_documentacion_de_mantenimiento_Mant_Condor_2024_2.pdf	Documentacion de mantenimiento	\N	database-relationed/aircraft/DTCON001-Condor/maintenance/5-2024-12-17/maintenance_5_documentacion_de_mantenimiento_Mant_Condor_2024_2.pdf	5
6	t	database-relationed/aircraft/DTCON001-Condor/maintenance/6-2025-12-19/maintenance_6_documentacion_de_mantenimiento_Mantenimiento_condor_2025.pdf	Documentacion de mantenimiento	\N	database-relationed/aircraft/DTCON001-Condor/maintenance/6-2025-12-19/maintenance_6_documentacion_de_mantenimiento_Mantenimiento_condor_2025.pdf	6
\.


--
-- Data for Name: notification_settings; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.notification_settings (notification_settings_id, certificate_first_days_ahead, certificate_second_days_ahead, event_days_ahead, last_run_date, maintenance_days_ahead, operation_days_ahead, schedule_hour, schedule_minute) FROM stdin;
1	30	7	1	2026-06-08	1	1	9	0
\.


--
-- Data for Name: operation; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.operation (id_operacion, anio_correlativo, codigo, conops, correlativo_anual, estado, fecha_actualizacion, fecha_creacion, user_id) FROM stdin;
7	2026	O-2026-001		1	EN_CURSO	2026-05-27 09:21:12.770574	2026-05-27 09:21:12.770574	9
13	2026	O-2026-002		2	EN_CURSO	2026-05-28 09:02:10.297643	2026-05-28 09:02:10.297643	9
\.


--
-- Data for Name: operation_assigned_users; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.operation_assigned_users (operation_id, user_id) FROM stdin;
\.


--
-- Data for Name: operation_documentation; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.operation_documentation (id, name) FROM stdin;
1	fdsafdsafdsa
2	19mb
5	21mb
6	fdsfafdsa
\.


--
-- Data for Name: personalExterno; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public."personalExterno" (anexo4_id, nombre_apellidos, rol, indice) FROM stdin;
3	mlnlnnjnnk	knllnnnlknlknlk	0
\.


--
-- Data for Name: sent_mail; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.sent_mail (sent_mail_id, header, recipient_mode, sent_at, body_text, sender_username) FROM stdin;
\.


--
-- Data for Name: sent_mail_recipients; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.sent_mail_recipients (sent_mail_id, recipient) FROM stdin;
\.


--
-- Data for Name: sent_mail_selected_roles; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.sent_mail_selected_roles (sent_mail_id, role) FROM stdin;
\.


--
-- Data for Name: sent_mail_selected_users; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.sent_mail_selected_users (sent_mail_id, username) FROM stdin;
\.


--
-- Data for Name: user_certificate; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.user_certificate (user_certificate_id, certificate_name, certificate_type, date_indefinite, expire_date, user_id) FROM stdin;
22	database-relationed/users/11-fdsafdsafds/certificates/a1a3/11-a1a3-19mb.pdf	a1a3	t	\N	11
23	database-relationed/users/11-fdsafdsafds/certificates/a2/user_11_a2.pdf	a2	f	\N	11
24	database-relationed/users/11-fdsafdsafds/certificates/sts/user_11_sts.pdf	sts	f	\N	11
\.


--
-- Name: aircraft_aircraft_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.aircraft_aircraft_id_seq', 6, true);


--
-- Name: aircraft_documentation_aircraft_documentation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.aircraft_documentation_aircraft_documentation_id_seq', 9, true);


--
-- Name: aircraft_model_documentation_aircraft_model_documentation_i_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.aircraft_model_documentation_aircraft_model_documentation_i_seq', 21, true);


--
-- Name: aircraft_model_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.aircraft_model_id_seq', 22, true);


--
-- Name: anexos_base_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.anexos_base_id_seq', 4, true);


--
-- Name: app_user_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.app_user_user_id_seq', 11, true);


--
-- Name: automatic_mail_preference_automatic_mail_preference_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.automatic_mail_preference_automatic_mail_preference_id_seq', 1, false);


--
-- Name: document_versions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.document_versions_id_seq', 6, true);


--
-- Name: extra_date_id_extra_date_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.extra_date_id_extra_date_seq', 1, false);


--
-- Name: flight_time_documentation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.flight_time_documentation_id_seq', 30, true);


--
-- Name: flight_time_flight_time_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.flight_time_flight_time_id_seq', 65, true);


--
-- Name: maintenance_documentation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.maintenance_documentation_id_seq', 6, true);


--
-- Name: maintenance_maintenance_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.maintenance_maintenance_id_seq', 8, true);


--
-- Name: operation_documentation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.operation_documentation_id_seq', 6, true);


--
-- Name: operation_id_operacion_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.operation_id_operacion_seq', 13, true);


--
-- Name: sent_mail_sent_mail_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.sent_mail_sent_mail_id_seq', 1, false);


--
-- Name: user_certificate_user_certificate_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.user_certificate_user_certificate_id_seq', 24, true);


--
-- Name: aircraft_documentation aircraft_documentation_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.aircraft_documentation
    ADD CONSTRAINT aircraft_documentation_pkey PRIMARY KEY (aircraft_documentation_id);


--
-- Name: aircraft_model_documentation aircraft_model_documentation_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.aircraft_model_documentation
    ADD CONSTRAINT aircraft_model_documentation_pkey PRIMARY KEY (aircraft_model_documentation_id);


--
-- Name: aircraft_model aircraft_model_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.aircraft_model
    ADD CONSTRAINT aircraft_model_pkey PRIMARY KEY (id);


--
-- Name: aircraft aircraft_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.aircraft
    ADD CONSTRAINT aircraft_pkey PRIMARY KEY (aircraft_id);


--
-- Name: anexo4_otras_limitaciones anexo4_otras_limitaciones_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.anexo4_otras_limitaciones
    ADD CONSTRAINT anexo4_otras_limitaciones_pkey PRIMARY KEY (anexo4_id, indice);


--
-- Name: anexo4 anexo4_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.anexo4
    ADD CONSTRAINT anexo4_pkey PRIMARY KEY (id);


--
-- Name: anexo5 anexo5_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.anexo5
    ADD CONSTRAINT anexo5_pkey PRIMARY KEY (id);


--
-- Name: anexo5_signed_users anexo5_signed_users_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.anexo5_signed_users
    ADD CONSTRAINT anexo5_signed_users_pkey PRIMARY KEY (anexo5_id, user_id);


--
-- Name: anexo6_elementos_auxiliares anexo6_elementos_auxiliares_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.anexo6_elementos_auxiliares
    ADD CONSTRAINT anexo6_elementos_auxiliares_pkey PRIMARY KEY (anexo6_id, indice);


--
-- Name: anexo6 anexo6_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.anexo6
    ADD CONSTRAINT anexo6_pkey PRIMARY KEY (id);


--
-- Name: anexo7 anexo7_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.anexo7
    ADD CONSTRAINT anexo7_pkey PRIMARY KEY (id);


--
-- Name: anexo8_otras_limitaciones anexo8_otras_limitaciones_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.anexo8_otras_limitaciones
    ADD CONSTRAINT anexo8_otras_limitaciones_pkey PRIMARY KEY (anexo8_id, indice);


--
-- Name: anexo8 anexo8_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.anexo8
    ADD CONSTRAINT anexo8_pkey PRIMARY KEY (id);


--
-- Name: anexos_base anexos_base_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.anexos_base
    ADD CONSTRAINT anexos_base_pkey PRIMARY KEY (id);


--
-- Name: app_user app_user_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_pkey PRIMARY KEY (user_id);


--
-- Name: app_user_roles app_user_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.app_user_roles
    ADD CONSTRAINT app_user_roles_pkey PRIMARY KEY (user_id, role);


--
-- Name: automatic_mail_preference automatic_mail_preference_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.automatic_mail_preference
    ADD CONSTRAINT automatic_mail_preference_pkey PRIMARY KEY (automatic_mail_preference_id);


--
-- Name: backup_settings backup_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.backup_settings
    ADD CONSTRAINT backup_settings_pkey PRIMARY KEY (backup_settings_id);


--
-- Name: document_versions document_versions_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.document_versions
    ADD CONSTRAINT document_versions_pkey PRIMARY KEY (id);


--
-- Name: extra_date extra_date_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.extra_date
    ADD CONSTRAINT extra_date_pkey PRIMARY KEY (id_extra_date);


--
-- Name: flight_time_documentation flight_time_documentation_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.flight_time_documentation
    ADD CONSTRAINT flight_time_documentation_pkey PRIMARY KEY (id);


--
-- Name: flight_time flight_time_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.flight_time
    ADD CONSTRAINT flight_time_pkey PRIMARY KEY (flight_time_id);


--
-- Name: maintenance_documentation maintenance_documentation_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.maintenance_documentation
    ADD CONSTRAINT maintenance_documentation_pkey PRIMARY KEY (id);


--
-- Name: maintenance maintenance_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.maintenance
    ADD CONSTRAINT maintenance_pkey PRIMARY KEY (maintenance_id);


--
-- Name: notification_settings notification_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.notification_settings
    ADD CONSTRAINT notification_settings_pkey PRIMARY KEY (notification_settings_id);


--
-- Name: operation_assigned_users operation_assigned_users_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.operation_assigned_users
    ADD CONSTRAINT operation_assigned_users_pkey PRIMARY KEY (operation_id, user_id);


--
-- Name: operation_documentation operation_documentation_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.operation_documentation
    ADD CONSTRAINT operation_documentation_pkey PRIMARY KEY (id);


--
-- Name: operation operation_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.operation
    ADD CONSTRAINT operation_pkey PRIMARY KEY (id_operacion);


--
-- Name: personalExterno personalExterno_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."personalExterno"
    ADD CONSTRAINT "personalExterno_pkey" PRIMARY KEY (anexo4_id, indice);


--
-- Name: sent_mail sent_mail_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.sent_mail
    ADD CONSTRAINT sent_mail_pkey PRIMARY KEY (sent_mail_id);


--
-- Name: app_user uk1j9d9a06i600gd43uu3km82jw; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT uk1j9d9a06i600gd43uu3km82jw UNIQUE (email);


--
-- Name: app_user uk3k4cplvh82srueuttfkwnylq0; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT uk3k4cplvh82srueuttfkwnylq0 UNIQUE (username);


--
-- Name: flight_time_documentation uk4e8jar6u4kmd9k5l54ftpaux7; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.flight_time_documentation
    ADD CONSTRAINT uk4e8jar6u4kmd9k5l54ftpaux7 UNIQUE (flight_time_id);


--
-- Name: maintenance_documentation uk7q4j62bewg11lfq5hleo2f7d2; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.maintenance_documentation
    ADD CONSTRAINT uk7q4j62bewg11lfq5hleo2f7d2 UNIQUE (maintenance_id);


--
-- Name: operation uk_operation_anio_correlativo; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.operation
    ADD CONSTRAINT uk_operation_anio_correlativo UNIQUE (anio_correlativo, correlativo_anual);


--
-- Name: operation uk_operation_codigo; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.operation
    ADD CONSTRAINT uk_operation_codigo UNIQUE (codigo);


--
-- Name: automatic_mail_preference ukex03kr2a0ing2t7jqi9s0y3qs; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.automatic_mail_preference
    ADD CONSTRAINT ukex03kr2a0ing2t7jqi9s0y3qs UNIQUE (user_id);


--
-- Name: app_user ukjkklld93fmfmfcfuo2dwh0el4; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT ukjkklld93fmfmfcfuo2dwh0el4 UNIQUE (doc_identidad);


--
-- Name: user_certificate user_certificate_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.user_certificate
    ADD CONSTRAINT user_certificate_pkey PRIMARY KEY (user_certificate_id);


--
-- Name: operation fk34miq7v2mk22l40oketymlmul; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.operation
    ADD CONSTRAINT fk34miq7v2mk22l40oketymlmul FOREIGN KEY (user_id) REFERENCES public.app_user(user_id);


--
-- Name: app_user_roles fk3lwiahkol5aetc57pto5olacf; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.app_user_roles
    ADD CONSTRAINT fk3lwiahkol5aetc57pto5olacf FOREIGN KEY (user_id) REFERENCES public.app_user(user_id);


--
-- Name: operation_assigned_users fk4p4r76uylbpj09b2m675nn8ij; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.operation_assigned_users
    ADD CONSTRAINT fk4p4r76uylbpj09b2m675nn8ij FOREIGN KEY (operation_id) REFERENCES public.operation(id_operacion);


--
-- Name: aircraft_model_documentation fk660mdk90c3wc4vxjparj0slwt; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.aircraft_model_documentation
    ADD CONSTRAINT fk660mdk90c3wc4vxjparj0slwt FOREIGN KEY (aircraft_model_id) REFERENCES public.aircraft_model(id);


--
-- Name: anexo5_signed_users fk76kpa97kqf556wg3pkqmnxmam; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.anexo5_signed_users
    ADD CONSTRAINT fk76kpa97kqf556wg3pkqmnxmam FOREIGN KEY (user_id) REFERENCES public.app_user(user_id);


--
-- Name: user_certificate fk7wu6169w7oqq1avgt80u6dumc; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.user_certificate
    ADD CONSTRAINT fk7wu6169w7oqq1avgt80u6dumc FOREIGN KEY (user_id) REFERENCES public.app_user(user_id);


--
-- Name: flight_time fk9r6o6gawuub1v4oom3bslrk44; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.flight_time
    ADD CONSTRAINT fk9r6o6gawuub1v4oom3bslrk44 FOREIGN KEY (aircraft_id) REFERENCES public.aircraft(aircraft_id);


--
-- Name: aircraft fk9xgy85yjaon792i9h138dqck2; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.aircraft
    ADD CONSTRAINT fk9xgy85yjaon792i9h138dqck2 FOREIGN KEY (aircraft_model_id) REFERENCES public.aircraft_model(id);


--
-- Name: anexo5 fkb8bdapp2r6geiqcqfa7elovo9; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.anexo5
    ADD CONSTRAINT fkb8bdapp2r6geiqcqfa7elovo9 FOREIGN KEY (id) REFERENCES public.anexos_base(id);


--
-- Name: anexo8_otras_limitaciones fkb91komoslfxlhxm2trdsdf87x; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.anexo8_otras_limitaciones
    ADD CONSTRAINT fkb91komoslfxlhxm2trdsdf87x FOREIGN KEY (anexo8_id) REFERENCES public.anexo8(id);


--
-- Name: aircraft_documentation fkbvgxsdddx7o1dne0ro35qt3av; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.aircraft_documentation
    ADD CONSTRAINT fkbvgxsdddx7o1dne0ro35qt3av FOREIGN KEY (aircraft_model_documentation_id) REFERENCES public.aircraft_model_documentation(aircraft_model_documentation_id);


--
-- Name: extra_date_roles fkd6h7hdu2k0vghq9uj32ub9ka7; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.extra_date_roles
    ADD CONSTRAINT fkd6h7hdu2k0vghq9uj32ub9ka7 FOREIGN KEY (extra_date_id) REFERENCES public.extra_date(id_extra_date);


--
-- Name: anexo5_signed_users fkd7shvb3vk7k5ymneb8v3wdry0; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.anexo5_signed_users
    ADD CONSTRAINT fkd7shvb3vk7k5ymneb8v3wdry0 FOREIGN KEY (anexo5_id) REFERENCES public.anexo5(id);


--
-- Name: maintenance fkdc1cu8p255p0dbaia32po5rpo; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.maintenance
    ADD CONSTRAINT fkdc1cu8p255p0dbaia32po5rpo FOREIGN KEY (aircraft_id) REFERENCES public.aircraft(aircraft_id);


--
-- Name: anexo4 fkdnhnh2q2pmruvsfklgl4d20re; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.anexo4
    ADD CONSTRAINT fkdnhnh2q2pmruvsfklgl4d20re FOREIGN KEY (id) REFERENCES public.anexos_base(id);


--
-- Name: sent_mail_recipients fke3p1s803axj0itx1elp5il5ki; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.sent_mail_recipients
    ADD CONSTRAINT fke3p1s803axj0itx1elp5il5ki FOREIGN KEY (sent_mail_id) REFERENCES public.sent_mail(sent_mail_id);


--
-- Name: anexo6_materiales_auxiliares fkg3wa6f9lbvsv8buywhivs29p; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.anexo6_materiales_auxiliares
    ADD CONSTRAINT fkg3wa6f9lbvsv8buywhivs29p FOREIGN KEY (anexo6_id) REFERENCES public.anexo6(id);


--
-- Name: sent_mail_selected_roles fkg9guswk63wasa6v8ex7j0rc7c; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.sent_mail_selected_roles
    ADD CONSTRAINT fkg9guswk63wasa6v8ex7j0rc7c FOREIGN KEY (sent_mail_id) REFERENCES public.sent_mail(sent_mail_id);


--
-- Name: document_versions fkgu4qnq1x0vuo7j0idv59mym5v; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.document_versions
    ADD CONSTRAINT fkgu4qnq1x0vuo7j0idv59mym5v FOREIGN KEY (documentation_id) REFERENCES public.operation_documentation(id);


--
-- Name: anexo6_elementos_auxiliares fkioxsgkvbq8v9kvq23sxnj2k8r; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.anexo6_elementos_auxiliares
    ADD CONSTRAINT fkioxsgkvbq8v9kvq23sxnj2k8r FOREIGN KEY (anexo6_id) REFERENCES public.anexo6(id);


--
-- Name: flight_time_documentation fkl2ppnqa1k6flt0b14wpjcgyw4; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.flight_time_documentation
    ADD CONSTRAINT fkl2ppnqa1k6flt0b14wpjcgyw4 FOREIGN KEY (flight_time_id) REFERENCES public.flight_time(flight_time_id);


--
-- Name: flight_time fkl72d7rx0r1swmfobftgkhntma; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.flight_time
    ADD CONSTRAINT fkl72d7rx0r1swmfobftgkhntma FOREIGN KEY (operation_id) REFERENCES public.operation(id_operacion);


--
-- Name: anexo7 fkl8exjimf9qp1a5w5s84ielt8o; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.anexo7
    ADD CONSTRAINT fkl8exjimf9qp1a5w5s84ielt8o FOREIGN KEY (id) REFERENCES public.anexos_base(id);


--
-- Name: automatic_mail_preference fkn9chtan28hhtoowo5mufc8xnr; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.automatic_mail_preference
    ADD CONSTRAINT fkn9chtan28hhtoowo5mufc8xnr FOREIGN KEY (user_id) REFERENCES public.app_user(user_id);


--
-- Name: sent_mail_selected_users fknf8o81q8j56s78t0mv4vxpr7v; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.sent_mail_selected_users
    ADD CONSTRAINT fknf8o81q8j56s78t0mv4vxpr7v FOREIGN KEY (sent_mail_id) REFERENCES public.sent_mail(sent_mail_id);


--
-- Name: operation_assigned_users fknmuh4qrfju535qikk0rjx0w5l; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.operation_assigned_users
    ADD CONSTRAINT fknmuh4qrfju535qikk0rjx0w5l FOREIGN KEY (user_id) REFERENCES public.app_user(user_id);


--
-- Name: maintenance_documentation fkpelv1um978va4cs6dxs30at35; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.maintenance_documentation
    ADD CONSTRAINT fkpelv1um978va4cs6dxs30at35 FOREIGN KEY (maintenance_id) REFERENCES public.maintenance(maintenance_id);


--
-- Name: anexo8 fkq3lx3us9bqcnljdbk8lo9511d; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.anexo8
    ADD CONSTRAINT fkq3lx3us9bqcnljdbk8lo9511d FOREIGN KEY (id) REFERENCES public.anexos_base(id);


--
-- Name: anexo4_otras_limitaciones fkqm2debdpsqek2xdghumdjhcnl; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.anexo4_otras_limitaciones
    ADD CONSTRAINT fkqm2debdpsqek2xdghumdjhcnl FOREIGN KEY (anexo4_id) REFERENCES public.anexo4(id);


--
-- Name: anexo6 fkry1iay2xbj2gxy26bh8rhc7u5; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.anexo6
    ADD CONSTRAINT fkry1iay2xbj2gxy26bh8rhc7u5 FOREIGN KEY (id) REFERENCES public.anexos_base(id);


--
-- Name: aircraft_documentation fks2rbpj6q4929ptddlffb3u01d; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.aircraft_documentation
    ADD CONSTRAINT fks2rbpj6q4929ptddlffb3u01d FOREIGN KEY (aircraft_id) REFERENCES public.aircraft(aircraft_id);


--
-- Name: personalExterno fksxq53favttcln58d7amv2gth8; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."personalExterno"
    ADD CONSTRAINT fksxq53favttcln58d7amv2gth8 FOREIGN KEY (anexo4_id) REFERENCES public.anexo4(id);


--
-- Name: anexos_base fktgqd85q62u1erhx4vk4v1vlu9; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.anexos_base
    ADD CONSTRAINT fktgqd85q62u1erhx4vk4v1vlu9 FOREIGN KEY (id_operacion) REFERENCES public.operation(id_operacion);


--
-- Name: anexo4_aircraft_ids fktqgkg8kkc9xcohpd45egh352y; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.anexo4_aircraft_ids
    ADD CONSTRAINT fktqgkg8kkc9xcohpd45egh352y FOREIGN KEY (anexo4_id) REFERENCES public.anexo4(id);


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: admin
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;


--
-- PostgreSQL database dump complete
--

\unrestrict u3HbdZlu1uchW7EN5GYIcb7CBFKNJzGbHhtq3F545BDFjhzgJUbofcW0n3GIyXR

